// <auto-generated />
namespace WebBanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class DatabseNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabseNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202503240144241_DatabseNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
